version: '3'

services: 
  redis: 
    container_name: redis-learning
    image: redis
    ports: 
      - "7379:6379"
    command: redis-server /etc/redis.conf
    volumes: 
      - "./redis-data:/data"
      - "./redis.conf:/etc/redis.conf"
    environment: 
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    restart: always
